spring:
  application: #微服务名称
    name: history-consumer
  cloud:
    inetutils:
      preferred-networks: 10.
#  redis:
#    cluster:
#      max-redirects: 6
#      nodes: 192.168.203.201:8001,192.168.203.202:8002,192.168.203.203:8003,192.168.203.201:8004,192.168.203.202:8005,192.168.203.203:8006
#  datasource:
#    username: root
#    password: zc123123
#    url: jdbc:mysql://localhost:3306/kafka
#    driver-class-name: com.mysql.cj.jdbc.Driver
#注册中心的地址 汇报心跳的时间
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${ZONE}
#      defaultZone: http://localhost:10086/eureka
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      buffered: false
      directory: /tmp/logs/history-consumer
      pattern: '%h %{X-Forwarded-For}i %l %u %t "%r" %b "%{Referer}i" "%{User-Agent}i" %s (%Dms)'
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true